[MDC-1010] simet-api: add report queue subsystem
Add a reports queue processing system.

simet_lmap-send-report.sh (the "report sink" as far as the lmapd
schedule is concerned) will compose/render the report into the reports
queue, and try to send it immediately.  Should that fail, the report
will be compressed and left in the queue for later sending.

simet_report-queue-flush.sh locates unsent reports in the queue, and
tries to send them all.  It should be run periodically.  The queue can
have subdirectories, if needed (this will be used later).

It also cleans up stale data (more than 24h old) in the queue that
doesn't match a compressed report filename.

simet_lmap-send-report.sh changed the behavior re. errors returned by
"lmapctl report": since version 0.15.0 of simet-lmapd, it will return a
non-zero status only if it cannot render *any* report at all, either
because *all* the input data was invalid, or the lmap subsystem
configuration is broken.  So, we now always return status zero if
we got that far, to erase likely invalid input data.

diff --git a/simet-api/simet_lmap-send-report.sh.in b/simet-api/simet_lmap-send-report.sh.in
--- a/simet-api/simet_lmap-send-report.sh.in
+++ b/simet-api/simet_lmap-send-report.sh.in
@@ -1,6 +1,6 @@
 #!/bin/bash
-# Send a LMAP report to a SIMET2 report collector
-# Copyright (c) 2019 NIC.br <medicoes@simet.nic.br>
+# Send a LMAP report to a SIMET2 report collector, or queue it
+# Copyright (c) 2019-2020 NIC.br <medicoes@simet.nic.br>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,14 +23,20 @@
 # Command line: list of URLs of collectors to use.  If none are given, the one
 # from the hardcoded configuration will be used.
 
+# The gzip-compressed report will be sent to stdout if no collectors
+# accept it.  If every collector rejects it as malformed, we consume (destroy)
+# it instead.  stdout should be redirected to a queue for later ressubmission,
+# skipping zero-sized/empty output files.
+
 set -e
 set -o pipefail
 
 . @SIMETLIBDIR@/simet_lib.sh || exit 3
 
+OUTFILE=
 abend() {
 	simet_log simet-ma daemon.err "$*"
-	[ -n "$OUTFILE" ] && rm -f "$OUTFILE" 2>/dev/null
+	[ -n "$OUTFILE" ] && rm -f "$OUTFILE" "$OUTFILE.gz" 2>/dev/null
 	exit 1
 }
 run_trap() {
@@ -41,17 +47,20 @@ run_trap() {
 # log errors.  Note: some versions of OpenWRT "find" lack -quit
 [ -z "$(find .. -maxdepth 1 -type f -name '*.data' -print | head -n1)" ] && exit 0
 
+if [ -z "$AGENT_ID_FILE" ] || [ -z "$AGENT_TOKEN_FILE" ] || [ -z "$LMAP_REPORT_QUEUE_DIR" ] ; then
+	abend "missing configuration: AGENT_ID_FILE, AGENT_TOKEN_FILE or LMAP_REPORT_QUEUE_DIR"
+fi
+
+[ -d "$LMAP_REPORT_QUEUE_DIR" ] || mkdir -m 0770 -p "$LMAP_REPORT_QUEUE_DIR"
+[ -d "$LMAP_REPORT_QUEUE_DIR" ] || abend "could not access $LMAP_REPORT_QUEUE_DIR"
+
+LMAPCTL=${LMAPCTL:-@BINDIR@/lmapctl}
+
 COLLECTORS=
 while [ $# -gt 0 ] ; do
 	COLLECTORS="$COLLECTORS $1"
 	shift
 done
-
-if [ -z "$AGENT_ID_FILE" ] || [ -z "$AGENT_TOKEN_FILE" ] ; then
-	abend "missing configuration: AGENT_ID_FILE or AGENT_TOKEN_FILE"
-fi
-LMAPCTL=${LMAPCTL:-@BINDIR@/lmapctl}
-
 [ -z "$COLLECTORS" ] &&	COLLECTORS="$LMAP_COLLECTOR"
 [ -z "$COLLECTORS" ] && abend "No LMAP collector specified"
 
@@ -60,18 +69,29 @@ CURLOPT="$CURL_APIOPT"
 
 # parameters: list of possible collectors to try to send to
 send_report_to_collector() {
+    malformed=0
     while [ $# -gt 0 ] ; do
-	curl $CURLOPT -A "$USERAGENT" \
-		--data-binary "@$OUTFILE" -f \
+	APIRES=$( curl $CURLOPT -A "$USERAGENT" \
+		--data-binary "@$OUTFILE" -X POST \
+		-o /dev/null -w "%{http_code}" \
 		-H "Authorization: Bearer $OLDAT" \
 		-H "Content-Type: application/yang.data+json" \
-		"$1" \
-	  && {
+		"$1" ) || APIRES=
+	case "$APIRES" in
+	200)
 		simet_log simet-ma daemon.info "LMAP report accepted by collector $1"
 		return 0
-	}
+		;;
+	400)
+		malformed=1
+		;;
+	esac
 	shift
     done
+    if [ "$malformed" -eq 1 ] ; then
+	simet_log simet-ma daemon.warn "LMAP report rejected as malformed by collectors, discarding it"
+	return 0
+    fi
     return 1
 }
 
@@ -82,7 +102,7 @@ OLDAID=
 
 # We *require* an agent-id and agent token to submit reports
 if [ -z "$OLDAT" ] || [ -z "$OLDAID" ] || [ ! -r "$LMAP_AGENT_FILE" ] ; then
-	abend "MA not registered yet, cannot submit reports"
+    abend "MA not registered yet, cannot submit reports"
 fi
 
 OUTFILE=$(mktemp -q -t simet-report.$$.XXXXXXXXXX) || abend "failed to create tmpfile"
@@ -90,9 +110,24 @@ OUTFILE=$(mktemp -q -t simet-report.$$.XXXXXXXXXX) || abend "failed to create tm
 # don't leave behind tmpfiles
 trap 'run_trap' INT TERM QUIT
 
-(export TZ=UTC0 && cd .. && $LMAPCTL -i json -j report) > $OUTFILE || abend "failed to render report"
-send_report_to_collector $COLLECTORS || abend "failed to submit report to collector"
-
-rm -f "$OUTFILE"
+OUTFILE=$(mktemp -q -p "$LMAP_REPORT_QUEUE_DIR" "simet-report.XXXXXXXXXX") || abend "failed to create tmpfile"
+if (export TZ=UTC0 && cd .. && $LMAPCTL -i json -j report) > "$OUTFILE" ; then
+    send_report_to_collector $COLLECTORS || {
+	# unsent, try to queue
+	if gzip "$OUTFILE" && mv -f "$OUTFILE.gz" "$OUTFILE.report.json.gz" ; then
+	    simet_log simet-ma daemon.debug "queued report: $OUTFILE.report.json.gz"
+	    OUTFILE=
+	else
+	    # FIXME: if we return non-zero status, there is no loss but we waste space
+	    # with the uncompressed report source data.  That would be *bad* since the
+	    # most likely reason for failure is full storage
+	    simet_log simet-ma daemon.err "could neither send nor compress report, report lost"
+	fi
+    }
+else
+    # Either all input is malformed, we have a bad lmap config, or ENOSPC
+    simet_log simet-ma daemon.err "failed to render report, report lost (likely invalid data)"
+fi
+[ -n "$OUTFILE" ] && rm -f "$OUTFILE" "$OUTFILE.gz"
 OUTFILE=
 :
