[MDC-501] simet-ma: simet-api: new Agent Registry and VLabel API
Switch simet*_register_ma to the new Agent Registry API, and
also add helpers to create and manage the MA virtual label used
to pair an MA with a "participant" (SIMET2 Web portal entity).

The files where agent-id and agent token are persisted have been
renamed.  This allows for a rollback strategy to the old API (which will
be disabled in the future) as well as a way to link the old agent-id to
the new one, preserving measurement history continuity.

diff --git a/simet-api/simet_register_ma.sh.in b/simet-api/simet_register_ma.sh.in
--- a/simet-api/simet_register_ma.sh.in
+++ b/simet-api/simet_register_ma.sh.in
@@ -18,44 +18,51 @@
 # parameters:
 #   --boot   (optional) shorten wait times and not restart the service
 
+set -e
+set -o pipefail
+
+RC=1
 OUTFILE=
 abend() {
-	simet_log simet-ma daemon.err "$*"
+	simet_log simet-ma daemon.err "error: $*"
 	[ -n "$OUTFILE" ] && rm -f "$OUTFILE" 2>/dev/null
-	exit 1
+	exit "$RC"
+}
+clean_exit() {
+	[ -n "$OUTFILE" ] && rm -f "$OUTFILE" 2>/dev/null
+	exit 0
 }
 
 is_call_implemented() {
-	command -V $1 > /dev/null 2>&1
+	command -V "$1" > /dev/null 2>&1
 }
 
 call() {
 	cmd="$1"
 	shift
-	if is_call_implemented ${cmd}_override ; then
-		${cmd}_override "$@"
+	if is_call_implemented "${cmd}_override" ; then
+		"${cmd}_override" "$@"
         else
-		${cmd} "$@"
+		"${cmd}" "$@"
 	fi
 }
 
 call_hook() {
 	cmd="$1"
 	shift
-	if is_call_implemented ${cmd} ; then
-		${cmd} "$@"
+	if is_call_implemented "${cmd}" ; then
+		"${cmd}" "$@"
 	fi
 }
 
 . @SIMETLIBDIR@/simet_lib.sh
 
-AGENT_ID_FILE=${AGENT_ID_FILE:-@SIMETCONFDIR@/agent-id}
-AGENT_TOKEN_FILE=${AGENT_TOKEN_FILE:-@SIMETCONFDIR@/agent.jwt}
-AGENT_TOKEN_LOCK=${AGENT_TOKEN_LOCK:-@LOCALSTATEDIR@/lock/simet-agent-token.lock}
-API_AGENT_TOKEN=${API_AGENT_TOKEN:-https://api.simet.nic.br/measurement/jwt}
-LMAP_AGENT_FILE=${LMAP_AGENT_FILE:-@SIMETCONFDIR@/lmap/agent-id.json}
+# FIXME: We can and should remove this after the "point of no return"
+# of support for downgrading without MA measurement continuity loss.
+V1_AGENT_ID_FILE="@SIMETCONFDIR@/agent-id"
+V1_AGENT_TOKEN_FILE="@SIMETCONFDIR@/agent.jwt"
+
 SIMETMA_RECONFIG=${SIMETMA_RECONFIG:-/etc/init.d/simet-ma reload}
-JSONFILTER=${JSONFILTER:-jsonfilter}
 
 # Load hooks and overrides
 [ -r @SIMETLIBDIR@/simet_register_ma-hooks.sh ] && . @SIMETLIBDIR@/simet_register_ma-hooks.sh
@@ -73,24 +80,73 @@ case "$1" in
 	;;
 esac
 
-#overridable
-simet_reginfo_api_call() {
-	curl $CURLOPT $CURLOPT2 -A "$USERAGENT" \
-		-X POST -f -o "$OUTFILE" \
-		-d simetAT="$OLDAT" -d "deviceInfo=$USERAGENT" \
-		"$API_AGENT_TOKEN"
-}
-
-#overridable
-simet_reginfo_api_parse() {
-	$JSONFILTER -i "$OUTFILE" -e "AID=@.agentId" -e "AT=@.token"
-}
+CURLOPT="$CURLOPT $CURLOPT2"
+CURLOPT2=
 
 #overridable
 simet_reginfo_restart_services() {
 	if [ -n "$SIMETMA_RECONFIG" ] ; then
 		$SIMETMA_RECONFIG || true
 	fi
+}
+
+#overridable
+simet_refresh_agent_status() {
+	APIRES=$( curl $CURLOPT -A "$USERAGENT" -H "X-SIMETBOX-ID: $BOXID" \
+		-H "Authorization: Bearer $OLDAT" \
+		-X GET -f -o "$OUTFILE" -w "%{http_code}" \
+		"${API_SIMET_AGENT_REG}/v2/agents/$OLDAID" ) || return 1
+	case "$APIRES" in
+	204)
+		#FIXME heal this, if it perdures for a while
+		abend "server doesn't know about us, need a registration reset!"
+		;;
+	403|401)
+		#FIXME heal this, if it perdures for a while
+		abend "registration too old, need a registration reset!"
+		;;
+	200)
+		return 0
+		;;
+	304)
+		clean_exit
+		;;
+	500|400)
+		abend "SIMET2 agent registry service unavailable"
+		;;
+        esac
+	return 1
+}
+
+__simet_create_agent_apicall() {
+	cat <<- EOFSCAG | \
+	  curl $CURLOPT \
+		-A "$USERAGENT" -H "X-SIMETBOX-ID: $BOXID" \
+		-H "Content-type: application/json" \
+		-f -X POST -o "$OUTFILE" -d @- -w "%{http_code}" \
+		"$API_SIMET_AGENT_REG/v2/agents" \
+	  || return 1
+	{ $*
+	  "engine_name":"@SIMET_ENGINE_NAME@",
+	  "engine_version":"@PACKAGEVERSION@",
+	  "agent_family":"$SIMET2_AGENT_FAMILY",
+	  "waiting_for_pairing":false }
+	EOFSCAG
+	:
+}
+#overridable
+simet_create_agent() {
+	V1AID=
+	V1AT=
+	V1JSON=
+	[ -r "$V1_AGENT_ID_FILE" ] && V1AID=$(cat "$V1_AGENT_ID_FILE")
+	[ -r "$V1_AGENT_TOKEN_FILE" ] && V1AT=$(cat "$V1_AGENT_TOKEN_FILE")
+	[ -n "$V1AID" ] && [ -n "$V1AT" ] && V1JSON="\"agent_id\":\"$V1AID\",\"agent_token\":\"$V1AT\","
+
+	# FIXME add healing strategy
+	APIRES=$(__simet_create_agent_apicall "$V1JSON") || return 1
+	[ "$APIRES" -eq 201 ] || return 1
+	:
 }
 
 gethash() {
@@ -127,9 +183,15 @@ gettoken() {
 	OUTFILE=$(mktemp -q -t simet-at-register.$$.XXXXXXXXXX) || abend "failed to create tmpfile"
 
 	call_hook before_reginfo_api_call
+	if [ -z "$OLDAT" ] || [ -z "$OLDAID" ] ; then
+		call simet_create_agent || abend "could not register measurement agent"
+	else
+		call simet_refresh_agent_status || abend "could not update registration"
+	fi
 
-	call simet_reginfo_api_call || abend "failed to contact agent-token service"
-	SID=$(call simet_reginfo_api_parse) || abend "illegal response from agent-token service"
+	PAIRED=0
+	SID=$($JSONFILTER -i "$OUTFILE" -e "AID=@.agent_id" -e "AT=@.agent_token" -e "PAIRED=@.has_pairing") \
+		|| abend "illegal response from agent-registry service"
 	eval "$SID" || abend "internal error"
 
 	call_hook before_reginfo_replace
@@ -154,6 +216,11 @@ gettoken() {
 	if [ ! -r "$AGENT_ID_FILE" ] || [ -z "$AID" ] || [ ! -r "$AGENT_TOKEN_FILE" ] || [ -z "$AT" ] ; then
 		call_hook failed_to_register
 		abend "failed to register, please retry later"
+	fi
+
+	# pairing
+	if [ "$PAIRED" != "true" ] ; then
+		@BINDIR@/simet_register_vlabel.sh || true
 	fi
 
 	if [ x"$AID" != x"$OLDAID" ] || [ x"$AT"  != x"$OLDAT"  ] ; then
diff --git a/simet-api/simetbox_register_ma.sh.in b/simet-api/simetbox_register_ma.sh.in
--- a/simet-api/simetbox_register_ma.sh.in
+++ b/simet-api/simetbox_register_ma.sh.in
@@ -15,34 +15,88 @@
 # General Public License and the COPYING file in the program Source
 # for details.
 
+set -e
+set -o pipefail
+
+RC=1
 OUTFILE=
 abend() {
-	simet_log simet-ma auth.err "$*"
+	simet_log simet-ma auth.err "error: $*"
 	[ -n "$OUTFILE" ] && rm -f "$OUTFILE" 2>/dev/null
-	exit 1
+	exit "$RC"
+}
+clean_exit() {
+	[ -n "$OUTFILE" ] && rm -f "$OUTFILE" 2>/dev/null
+	exit 0
 }
 
 . @SIMETLIBDIR@/simet_lib.sh
 
-AGENT_ID_FILE=${AGENT_ID_FILE:-@SIMETCONFDIR@/agent-id}
-AGENT_TOKEN_FILE=${AGENT_TOKEN_FILE:-@SIMETCONFDIR@/agent.jwt}
-AGENT_TOKEN_LOCK=${AGENT_TOKEN_LOCK:-@LOCALSTATEDIR@/lock/simet-agent-token.lock}
-API_AGENT_TOKEN=${API_AGENT_TOKEN:-https://api.simet.nic.br/measurement/jwt}
+# FIXME: We can and should remove this after the "point of no return"
+# of support for downgrading without MA measurement continuity loss.
+V1_AGENT_ID_FILE="@SIMETCONFDIR@/agent-id"
+V1_AGENT_TOKEN_FILE="@SIMETCONFDIR@/agent.jwt"
 
-LMAP_AGENT_FILE=${LMAP_AGENT_FILE:-@SIMETCONFDIR@/lmap/agent-id.json}
 SIMETMA_RECONFIG=${SIMETMA_RECONFIG:-/etc/init.d/simet-ma reload}
-JSONFILTER=${JSONFILTER:-jsonfilter}
 
 USERAGENT=$(get_http_useragent)
 CURLOPT="$CURL_APIOPT --max-filesize 4000"
 
-apicall() {
-	until curl $CURLOPT -A "$USERAGENT" -H "X-SIMETBOX-ID: $BOXID" \
-		-X POST -f -o "$OUTFILE" \
-		-d simetAT="$OLDAT" -d "deviceInfo=$USERAGENT" \
-		"$API_AGENT_TOKEN" ; do
-			sleep 14400
-	done
+simet_refresh_agent_status() {
+	APIRES=$( curl $CURLOPT -A "$USERAGENT" -H "X-SIMETBOX-ID: $BOXID" \
+		-H "Authorization: Bearer $OLDAT" \
+		-X GET -f -o "$OUTFILE" -w "%{http_code}" \
+		"${API_SIMET_AGENT_REG}/v2/agents/$OLDAID" ) || return 1
+	case "$APIRES" in
+	204)
+		#FIXME heal this, if it perdures for a while
+		abend "server doesn't know about us, need a registration reset!"
+		;;
+	403|401)
+		#FIXME heal this, if it perdures for a while
+		abend "registration too old, need a registration reset!"
+		;;
+	200)
+		return 0
+		;;
+	304)
+		clean_exit
+		;;
+	500|400)
+		abend "SIMET2 agent registry service unavailable"
+		;;
+        esac
+	return 1
+}
+
+__simet_create_agent_apicall() {
+	cat <<- EOFSCAG | \
+	  curl $CURLOPT --retry 30 --retry-max-time 300 \
+		-A "$USERAGENT" -H "X-SIMETBOX-ID: $BOXID" \
+		-H "Content-type: application/json" \
+		-f -X POST -o "$OUTFILE" -d @- -w "%{http_code}" \
+		"$API_SIMET_AGENT_REG/v2/agents" \
+	  || return 1
+	{ $*
+	  "engine_name":"@SIMET_ENGINE_NAME@",
+	  "engine_version":"@PACKAGEVERSION@",
+	  "agent_family":"$SIMET2_AGENT_FAMILY",
+	  "waiting_for_pairing":false }
+	EOFSCAG
+	:
+}
+simet_create_agent() {
+	V1AID=
+	V1AT=
+	V1JSON=
+	[ -r "$V1_AGENT_ID_FILE" ] && V1AID=$(cat "$V1_AGENT_ID_FILE")
+	[ -r "$V1_AGENT_TOKEN_FILE" ] && V1AT=$(cat "$V1_AGENT_TOKEN_FILE")
+	[ -n "$V1AID" ] && [ -n "$V1AT" ] && V1JSON="\"agent_id\":\"$V1AID\",\"agent_token\":\"$V1AT\","
+
+	# FIXME add healing strategy
+	APIRES=$(__simet_create_agent_apicall "$V1JSON") || return 1
+	[ "$APIRES" -eq 201 ] || return 1
+	:
 }
 
 gethash() {
@@ -77,8 +131,16 @@ gettoken() {
 	[ -r "$AGENT_TOKEN_FILE" ] && OLDAT=$(cat "$AGENT_TOKEN_FILE")
 
 	OUTFILE=$(mktemp -q -t simet-at-register.$$.XXXXXXXXXX) || abend "failed to create tmpfile"
-	apicall || abend "failed to contact agent-token service"
-	SID=$($JSONFILTER -i "$OUTFILE" -e "AID=@.agentId" -e "AT=@.token") || abend "illegal response from agent-token service"
+
+	if [ -z "$OLDAT" ] || [ -z "$OLDAID" ] ; then
+		simet_create_agent || abend "could not register measurement agent"
+	else
+		simet_refresh_agent_status || abend "could not update registration"
+	fi
+
+	PAIRED=0
+	SID=$($JSONFILTER -i "$OUTFILE" -e "AID=@.agent_id" -e "AT=@.agent_token" -e "PAIRED=@.has_pairing") \
+		|| abend "illegal response from agent-registry service"
 	eval "$SID" || abend "internal error"
 
 	[ x"$AID" != x"$OLDAID" ] && echo "$AID" > "$AGENT_ID_FILE"
@@ -91,6 +153,11 @@ gettoken() {
 
 	if [ ! -r "$AGENT_ID_FILE" ] || [ -z "$AID" ] || [ ! -r "$AGENT_TOKEN_FILE" ] || [ -z "$AT" ] ; then
 		abend "failed to register, please retry later"
+	fi
+
+	# pairing
+	if [ "$PAIRED" != "true" ] ; then
+		simet_register_vlabel.sh || true
 	fi
 
 	if [ x"$AID" != x"$OLDAID" ] || [ x"$AT"  != x"$OLDAT"  ] ; then
