[MDC-865] simet-api: simet_register_ma: layerize cred file writes
Have all cretential file writes/erasing done by single function
(overridable), so that we can better extend it with metadata through
hooks.

diff --git a/simet-api/simet_register_ma.sh.in b/simet-api/simet_register_ma.sh.in
--- a/simet-api/simet_register_ma.sh.in
+++ b/simet-api/simet_register_ma.sh.in
@@ -81,6 +81,7 @@ __gethash() {
 	return 0
 }
 #overidable
+#clobbers $OUTFILE contents!
 write_lmap_agent() {
 	if [ -z "$1" ] ; then
 		rm -f  "$LMAP_AGENT_FILE"
@@ -99,6 +100,34 @@ write_lmap_agent() {
 	fi
 	:
 }
+#overridable
+# $1: VTK (assumed to be stored in tmpfs)
+write_access_tokens() {
+	if [ -z "$1" ] ; then
+		rm -f "$AGENT_VTK_FILE"
+		simet_log simet-ma daemon.notice "SIMET: view_results token removed"
+	else
+		printf "%s" "$1" > "$AGENT_VTK_FILE"
+		simet_log simet-ma daemon.info "SIMET: view_results token updated"
+	fi
+	:
+}
+#overridable
+#clobbers $OUTFILE contents (write_lmap_agent)
+write_agent_creds() {
+	if [ -z "$AID" ] ; then
+		rm -f "$AGENT_ID_FILE"
+	elif [ "$AID" != "$OLDAID" ] ; then
+		printf '%s\n' "$AID" > "$AGENT_ID_FILE"
+	fi
+	if [ -z "$AT" ] ; then
+		rm -f "$AGENT_TOKEN_FILE"
+	elif [ "$AT"  != "$OLDAT"  ] ; then
+		printf '%s\n' "$AT" > "$AGENT_TOKEN_FILE"
+	fi
+	call write_lmap_agent "$AID" || :
+	:
+}
 
 #must not change pairing data cache
 __simet_consume_api_output() {
@@ -109,15 +138,10 @@ __simet_consume_api_output() {
 		|| abend "illegal response from agent-registry service"
 	eval "$SID" || abend "internal error"
 	PAIREDTO=$($JSONFILTER -i "$OUTFILE" -e "@.participant_id") || PAIREDTO=
-
-	[ x"$AID" != x"$OLDAID" ] && {
-		echo "$AID" > "$AGENT_ID_FILE"
-		call write_lmap_agent "$AID" || :
-		# OUTFILE not valid anymore!
-	}
-	[ x"$AT"  != x"$OLDAT"  ] && echo "$AT" > "$AGENT_TOKEN_FILE"
-
 	: > "$OUTFILE"
+
+	call write_agent_creds || \
+		simet_log simet-ma daemon.err "failed to write credentials!"
 	:
 }
 
@@ -344,16 +368,14 @@ simet_pairing_flow() {
 }
 
 __consume_tokens_api_output() {
+	VTK=
 	SID=$($JSONFILTER -i "$OUTFILE" -e "VTK=@.access_tokens.view_results") \
 		|| abend "illegal response from agent-registry service"
 	eval "$SID" || abend "internal error"
-
-	printf "%s" "$VTK" > "$AGENT_VTK_FILE" || \
-		simet_log simet-ma daemon.err "SIMET-MA: failed to store view_results token"
-
-	simet_log simet-ma daemon.info "SIMET: view_results token updated"
-
 	: > "$OUTFILE"
+
+	call write_access_tokens "$VTK" || \
+		simet_log simet-ma daemon.err "failed to store access tokens"
 	:
 }
 
