[MDC-799] simet-ma: require config files
Remove the use of shell defaults for config items.  Instead, require
that they be correctly set on the config file, and issue error messages
accordingly.

Helps the debugging of issues caused by broken/missing config files.

diff --git a/debian/simet-lmapd.init b/debian/simet-lmapd.init
--- a/debian/simet-lmapd.init
+++ b/debian/simet-lmapd.init
@@ -35,10 +35,10 @@ DAEMON_ARGS="-j"
 do_start_prepare() {
 	[ -r /opt/simet/lib/simet/simet-ma.conf ] && . /opt/simet/lib/simet/simet-ma.conf
 	[ -r /opt/simet/etc/simet/simet-ma.conf ] && . /opt/simet/etc/simet/simet-ma.conf
-	LMAP_QUEUE_DIR="${LMAP_QUEUE_DIR:-/var/spool/lmapd/queue}"
-	LMAP_SCHEDULE_FILE="${LMAP_SCHEDULE_FILE:-/var/run/lmapd/lmap-schedule.json}"
-	LMAP_AGENT_FILE="${LMAP_AGENT_FILE:-/opt/simet/etc/simet/lmap/agent-id.json}"
-
+	if [ -z "$LMAP_QUEUE_DIR" ] || [ -z "$LMAP_SCHEDULE_FILE" ] || [ -z "$LMAP_AGENT_FILE" ] ; then
+		echo "$0: required configuration missing, aborting..." >&2
+		return 1
+	fi
 	LMAP_SCHEDULE_DIR=$(dirname "$LMAP_SCHEDULE_FILE")
 
 	mkdir -p "$PID_DIR"
diff --git a/debian/simet-ma.init b/debian/simet-ma.init
--- a/debian/simet-ma.init
+++ b/debian/simet-ma.init
@@ -29,11 +29,12 @@ START_ARGS="-u $USER -c $USER --background --make-pidfile"
 
 [ -r /opt/simet/lib/simet/simet-ma.conf ] && . /opt/simet/lib/simet/simet-ma.conf
 [ -r /opt/simet/etc/simet/simet-ma.conf ] && . /opt/simet/etc/simet/simet-ma.conf
-AGENT_ID_FILE=${AGENT_ID_FILE:-/opt/simet/etc/simet/agent-id}
-AGENT_TOKEN_FILE=${AGENT_TOKEN_FILE:-/opt/simet/etc/simet/agent.jwt}
-SIMET_INETUP_SERVER=${SIMET_INETUP_SERVER:-simet-monitor-inetup.simet.nic.br}
+if [ -z "$AGENT_ID_FILE" ] || [ -z "$AGENT_TOKEN_FILE" ] || \
+   [ -z "$GEOLOC_CACHE" ] || [ -z "$SIMET_INETUP_SERVER" ] ; then
+	echo "$0: required configuration missing, aborting..." >&2
+	exit 1
+fi
 BOOTID=$(cat /proc/sys/kernel/random/boot_id) || true
-GEOLOC_CACHE=${GEOLOC_CACHE:-/var/run/simet/geoloc-cache.txt}
 
 DAEMON_ARGS="-M ${LMAP_TASK_NAME_PREFIX}inetconn-state -b $BOOTID"
 [ -r "$AGENT_TOKEN_FILE" ] && DAEMON_ARGS="$DAEMON_ARGS -j $(cat $AGENT_TOKEN_FILE)"
