[MDC-1427] deb: grant CAP_NET_RAW to sspooferc
Attempt to give CAP_NET_RAW=ep filesystem capabilities to sspooferc at
service start, and also package install.

This allows the sspoofer measurement (BCP38v2) to run as a non-root
user.

diff --git a/debian/simet-ma.init b/debian/simet-ma.init
--- a/debian/simet-ma.init
+++ b/debian/simet-ma.init
@@ -59,6 +59,15 @@ fix_traceroute() {
     :
 }
 
+fix_sspooferc() {
+    command -v setcap >/dev/null 2>&1 && setcap -q -v cap_net_raw+ep /opt/simet/bin/sspooferc || {
+	echo "$0: giving /opt/simet/bin/sspooferc CAP_NET_RAW capabilities for non-root measurement" >&2
+	setcap -q cap_net_raw+ep /opt/simet/bin/sspooferc || \
+	    echo "$0: failed to change /opt/simet/bin/sspooferc capabilities" >&2
+    }
+    :
+}
+
 # We *really* need bigger buffers for high-BDP, and unfortunately
 # due to several issues in many versions of the Linux kernels, it
 # has to already start big.  And we need some tricks because /bin/sh
@@ -175,6 +184,7 @@ do_stop_cmd_override() {
 #   2 if daemon could not be started
 do_start_cmd_override() {
 	fix_traceroute
+	fix_sspoofer
 	fix_tcp
 
 	start-stop-daemon --start --quiet --pidfile "${PIDFILE}" \
diff --git a/debian/simet-ma.postinst b/debian/simet-ma.postinst
--- a/debian/simet-ma.postinst
+++ b/debian/simet-ma.postinst
@@ -55,6 +55,15 @@ fix_traceroute() {
     :
 }
 
+fix_sspooferc() {
+    command -v setcap >/dev/null 2>&1 && setcap -q -v cap_net_raw+ep /opt/simet/bin/sspooferc || {
+	echo "$0: giving /opt/simet/bin/sspooferc CAP_NET_RAW capabilities for non-root measurement" >&2
+	setcap -q cap_net_raw+ep /opt/simet/bin/sspooferc || \
+	    echo "$0: failed to change /opt/simet/bin/sspooferc capabilities" >&2
+    }
+    :
+}
+
 # Refer to:
 #  - https://scotthelme.co.uk/lets-encrypt-old-root-expiration/
 #  - https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/
@@ -93,6 +102,7 @@ case "$1" in
 
 	fix_traceroute
 	fix_letsencrypt
+	fix_sspooferc
 
 	# Remove any downloaded schedule, lastrun data
 	rm -f /var/run/lmapd/*.json
