[MDC-1026] simet-api,deb: simet_lib*: defend against config syntax errors
Unless we go to extreme lengths, it is quite hard to ensure the shell
won't abort on us when sourcing the configuration files.  We can try,
though...

This change requires some updates to the packaging scripts that call
simet_lib-config.sh, otherwise they'd not benefit any from the change
(but it wouldn't break them, either).

diff --git a/debian/simet-lmapd.init b/debian/simet-lmapd.init
--- a/debian/simet-lmapd.init
+++ b/debian/simet-lmapd.init
@@ -33,9 +33,14 @@ DAEMON_ARGS="-j"
 
 # not called on default init-d-script do_restart/reload
 do_start_prepare() {
-	RC=0
-	. /opt/simet/lib/simet/simet_lib_config.sh || RC=$?
-	if [ $RC -ne 0 ] || [ -z "$LMAP_QUEUE_DIR" ] || [ -z "$LMAP_SCHEDULE_FILE" ] || [ -z "$LMAP_AGENT_FILE" ] ; then
+	# SIMET_CFG_LOAD_ERROR is also internally set in simet_lib_config.sh
+	SIMET_CFG_LOAD_ERROR=
+	. /opt/simet/lib/simet/simet_lib_config.sh || SIMET_CFG_LOAD_ERROR=1
+	if [ -n "$SIMET_CFG_LOAD_ERROR" ] ; then
+		echo "$0: syntax errors in the configuration files, aborting..." >&2
+		return 1
+	fi
+	if [ -z "$LMAP_QUEUE_DIR" ] || [ -z "$LMAP_SCHEDULE_FILE" ] || [ -z "$LMAP_AGENT_FILE" ] ; then
 		echo "$0: required configuration missing, aborting..." >&2
 		return 1
 	fi
diff --git a/debian/simet-ma.init b/debian/simet-ma.init
--- a/debian/simet-ma.init
+++ b/debian/simet-ma.init
@@ -27,9 +27,14 @@ PIDFILE=/var/run/simet-inetupc.pid
 
 START_ARGS="-u $SUSER -c $SUSER --background --make-pidfile"
 
-RC=0
-. /opt/simet/lib/simet/simet_lib_config.sh || RC=$?
-if [ $RC -ne 0 ] || [ -z "$AGENT_ID_FILE" ] || [ -z "$AGENT_TOKEN_FILE" ] || \
+# SIMET_CFG_LOAD_ERROR is also internally set in simet_lib_config.sh
+SIMET_CFG_LOAD_ERROR=
+. /opt/simet/lib/simet/simet_lib_config.sh || SIMET_CFG_LOAD_ERROR=1
+if [ -n "$SIMET_CFG_LOAD_ERROR" ] ; then
+	echo "$0: syntax errors in the configuration files, aborting..." >&2
+	exit 1
+fi
+if [ -z "$AGENT_ID_FILE" ] || [ -z "$AGENT_TOKEN_FILE" ] || \
    [ -z "$GEOLOC_CACHE" ] || [ -z "$SIMET_INETUP_SERVER" ] ; then
 	echo "$0: required configuration missing, aborting..." >&2
 	exit 1
